[tox]
requires =
    tox>=4
env_list = py3,pep8,cover
ignore_basepython_conflict = True

[testenv]
basepython = python3
setenv =
    VIRTUAL_ENV={envdir}
    LANGUAGE=C.UTF-8
    LC_ALL=C.UTF-8
    OS_LOG_CAPTURE={env:OS_LOG_CAPTURE:true}
    OS_STDOUT_CAPTURE={env:OS_STDOUT_CAPTURE:true}
    OS_STDERR_CAPTURE={env:OS_STDERR_CAPTURE:true}
    OS_TEST_TIMEOUT={env:OS_TEST_TIMEOUT:180}
    PYTHONDONTWRITEBYTECODE=1
passenv =
    http_proxy
    HTTP_PROXY
    https_proxy
    HTTPS_PROXY
    no_proxy
    NO_PROXY
    OS_DEBUG
usedevelop = True
commands =
    stestr run {posargs}
    stestr slowest
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
allowlist_externals =
    rm
    stestr

[testenv:pep8]
commands =
    flake8 sieve_cache

[testenv:venv]
commands = {posargs}

[testenv:cover]
setenv =
    {[testenv]setenv}
    PYTHON=coverage run --source sieve_cache --parallel-mode
commands =
    coverage erase
    stestr run --no-subunit-trace {posargs}
    coverage combine
    coverage html -d cover
    coverage xml -o cover/coverage.xml
    coverage report --fail-under=70 --skip-covered
